name: "Release"

on:
  workflow_dispatch:

jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: "Install dependencies"
        run: npm ci

      - name: "Build project"
        run: npm run build

      - name: "Archive build artifacts"
        run: |
          mkdir -p dist
          zip -r dist/build.zip dist

      - name: "Run semantic-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/build.zip
